export const buildWebviewBridgeScript = (sourceOrigin: string) => [
  "const vscode = acquireVsCodeApi();",
  "const codexhubFrame = document.getElementById('codexhubFrame');",
  `const codexhubOrigin = ${JSON.stringify(sourceOrigin).replaceAll("<", "\\u003c")};`,
  "const pendingCodexHubMessages = [];",
  "let codexhubFrameLoaded = false;",
  "const postToCodexHubFrame = (data) => {",
  "  if (!codexhubFrameLoaded) {",
  "    pendingCodexHubMessages.push(data);",
  "    return;",
  "  }",
  "  codexhubFrame.contentWindow?.postMessage(data, codexhubOrigin);",
  "};",
  "const isHttpUrl = (value) => {",
  "  if (typeof value !== 'string') return false;",
  "  try {",
  "    const protocol = new URL(value.trim()).protocol;",
  "    return protocol === 'http:' || protocol === 'https:';",
  "  } catch {",
  "    return false;",
  "  }",
  "};",
  "codexhubFrame.addEventListener('load', () => {",
  "  codexhubFrameLoaded = true;",
  "  while (pendingCodexHubMessages.length) postToCodexHubFrame(pendingCodexHubMessages.shift());",
  "});",
  "window.addEventListener('message', (event) => {",
  "  const data = event.data;",
  "  if (!data) return;",
  "  if (event.source === codexhubFrame.contentWindow && event.origin === codexhubOrigin) {",
  "    if (data.type === 'codexhub.openExternal') {",
  "      if (!isHttpUrl(data.url)) return;",
  "      vscode.postMessage({ type: data.type, url: data.url.trim() });",
  "      return;",
  "    }",
  "    if (data.type !== 'codexhub.taskCompleteNotification' && data.type !== 'codexhub.openFile' && data.type !== 'codexhub.recoverSurface') return;",
  "    vscode.postMessage(data);",
  "    return;",
  "  }",
  "  if (data.type === 'codexhub.addTextAttachment' || data.type === 'codexhub.openThread') postToCodexHubFrame(data);",
  "});"
].join("\n");
