export const buildWebviewBridgeScript = (sourceOrigin: string, theiaHost: boolean) => [
  "const vscode = acquireVsCodeApi();",
  "const codexhubFrame = document.getElementById('codexhubFrame');",
  `const codexhubOrigin = ${JSON.stringify(sourceOrigin).replaceAll("<", "\\u003c")};`,
  `const codexhubTheiaHost = ${JSON.stringify(theiaHost)};`,
  "const pendingCodexHubMessages = [];",
  "let codexhubFrameLoaded = false;",
  "const postToCodexHubFrame = (data) => {",
  "  if (!codexhubFrameLoaded) {",
  "    pendingCodexHubMessages.push(data);",
  "    return;",
  "  }",
  "  codexhubFrame.contentWindow?.postMessage(data, codexhubOrigin);",
  "};",
  "codexhubFrame.addEventListener('load', () => {",
  "  codexhubFrameLoaded = true;",
  "  while (pendingCodexHubMessages.length) postToCodexHubFrame(pendingCodexHubMessages.shift());",
  "});",
  "const requestCodexHubNotificationPermission = () => {",
  "  if (!codexhubTheiaHost || typeof Notification !== 'function' || Notification.permission !== 'default') return;",
  "  void Promise.resolve(Notification.requestPermission()).catch(() => undefined);",
  "};",
  "const showCodexHubNotification = (data) => {",
  "  if (!codexhubTheiaHost || typeof Notification !== 'function' || Notification.permission !== 'granted') return false;",
  "  const payload = data && typeof data.notification === 'object' ? data.notification : null;",
  "  const threadId = typeof payload?.threadId === 'string' ? payload.threadId.trim() : '';",
  "  if (!threadId) return false;",
  "  try {",
  "    const notification = new Notification(typeof payload.title === 'string' ? payload.title : 'Codex task complete', {",
  "      body: typeof payload.body === 'string' ? payload.body : '',",
  "      tag: 'codexhub-task-complete:' + threadId",
  "    });",
  "    notification.onclick = () => {",
  "      notification.close();",
  "      window.focus();",
  "      vscode.postMessage({ type: 'codexhub.notificationClicked', threadId });",
  "    };",
  "    return true;",
  "  } catch {",
  "    return false;",
  "  }",
  "};",
  "window.addEventListener('message', (event) => {",
  "  const data = event.data;",
  "  if (!data) return;",
  "  if (event.source === codexhubFrame.contentWindow && event.origin === codexhubOrigin) {",
  "    if (data.type === 'codexhub.requestNotificationPermission') {",
  "      requestCodexHubNotificationPermission();",
  "      return;",
  "    }",
  "    if (data.type === 'codexhub.taskCompleteNotification' && showCodexHubNotification(data)) return;",
  "    if (data.type !== 'codexhub.taskCompleteNotification' && data.type !== 'codexhub.openFile') return;",
  "    vscode.postMessage(data);",
  "    return;",
  "  }",
  "  if (data.type === 'codexhub.addTextAttachment' || data.type === 'codexhub.openThread') postToCodexHubFrame(data);",
  "});"
].join("\n");
